sudo: required
services:
  - docker

before_install:
  # Use encrypted google cloud service-account.json.enc file to login
  # File was generated
  #   -> Created IAM account on gcloud and downloaded service-account.json
  #   -> Open travis CLI in a ruby:2.4 docker image
  #   -> Log into travis and encrypt service-account.json and get service-account.json.enc
  #   -> Resulting command is from the output of the encryption
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Setup GCLoud CLI on travis
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud/sdk/path.bash.inc
  - gcloud components update kubectl
  # Log into gcloud with gcloud IAM account
  - gcloud auth activate-service-account --key-file service-account.json